#pragma once
// Stub: eVehicleModel enum for unit tests.
// Starting at 90; only the values GangInfo.cpp actually uses are listed.
enum eVehicleModel : unsigned int {
    MODEL_LANDSTAL = 90,
    MODEL_IDAHO, MODEL_STINGER, MODEL_LINERUN, MODEL_PEREN, MODEL_SENTINEL,
    MODEL_PATRIOT, MODEL_FIRETRUK, MODEL_TRASH, MODEL_STRETCH, MODEL_MANANA,
    MODEL_INFERNUS, MODEL_BLISTA, MODEL_PONY, MODEL_MULE, MODEL_CHEETAH,
    MODEL_AMBULAN, MODEL_FBICAR, MODEL_MOONBEAM, MODEL_ESPERANT, MODEL_TAXI,
    MODEL_KURUMA, MODEL_BOBCAT, MODEL_MRWHOOP, MODEL_BFINJECT, MODEL_CORPSE,
    MODEL_POLICE, MODEL_ENFORCER, MODEL_SECURICA, MODEL_BANSHEE, MODEL_PREDATOR,
    MODEL_BUS, MODEL_RHINO, MODEL_BARRACKS, MODEL_TRAIN, MODEL_CHOPPER,
    MODEL_DODO, MODEL_COACH, MODEL_CABBIE, MODEL_STALLION, MODEL_RUMPO,
    MODEL_RCBANDIT, MODEL_BELLYUP, MODEL_MRWONGS,
    MODEL_MAFIA,   // 134
    MODEL_YARDIE,  // 135
    MODEL_YAKUZA,  // 136
    MODEL_DIABLOS, // 137
};
